[2021-12-03 11:39:14,869] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: poc_dag.downloading_data manual__2021-12-03T11:39:13.520735+00:00 [queued]>
[2021-12-03 11:39:14,884] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: poc_dag.downloading_data manual__2021-12-03T11:39:13.520735+00:00 [queued]>
[2021-12-03 11:39:14,884] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-03 11:39:14,884] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-03 11:39:14,884] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-03 11:39:14,896] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): downloading_data> on 2021-12-03 11:39:13.520735+00:00
[2021-12-03 11:39:14,903] {standard_task_runner.py:52} INFO - Started process 117 to run task
[2021-12-03 11:39:14,907] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'poc_dag', 'downloading_data', 'manual__2021-12-03T11:39:13.520735+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/poc_dag.py', '--cfg-path', '/tmp/tmphpfsz9cz', '--error-file', '/tmp/tmpvdoji3pl']
[2021-12-03 11:39:14,908] {standard_task_runner.py:77} INFO - Job 10: Subtask downloading_data
[2021-12-03 11:39:15,061] {logging_mixin.py:109} INFO - Running <TaskInstance: poc_dag.downloading_data manual__2021-12-03T11:39:13.520735+00:00 [running]> on host f4a422e3c3b1
[2021-12-03 11:39:15,420] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=poc_dag
AIRFLOW_CTX_TASK_ID=downloading_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-03T11:39:13.520735+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-03T11:39:13.520735+00:00
[2021-12-03 11:39:15,422] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-03 11:39:15,423] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-12-03 11:39:15,439] {subprocess.py:85} INFO - Output:
[2021-12-03 11:39:18,443] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-03 11:39:18,517] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=poc_dag, task_id=downloading_data, execution_date=20211203T113913, start_date=20211203T113914, end_date=20211203T113918
[2021-12-03 11:39:18,577] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-03 11:39:18,661] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
